version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - '${MONGO_PORT_NUMBER}:27017'
    volumes:
      - './data:/data/db'
  app:
    ports:
      - 8080:8080
    build: .
    environment:
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_PORT_NUMBER: ${MONGO_PORT_NUMBER}
      APP_PORT_NUMBER: ${APP_PORT_NUMBER}
    depends_on:
      - mongodb_container
    network_mode: "host"  